Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/stylesheets/application.scss
app/views/kaminari/_first_page.html.erb
app/views/kaminari/_gap.html.erb
app/views/kaminari/_last_page.html.erb
app/views/kaminari/_next_page.html.erb
app/views/kaminari/_page.html.erb
app/views/kaminari/_paginator.html.erb
app/views/kaminari/_prev_page.html.erb
config/initializers/kaminari_config.rb

テーブル定義書に記載してあるgemを一通りインストールしました

[Add]Install Gems

---

app/models/customer.rb
db/migrate/20210816071226_devise_create_customers.rb
db/migrate/20210816085731_add_columns_to_customer.rb
db/migrate/20210816093119_rename_is_deleted_column_to_customers.rb
db/schema.rb
test/fixtures/customers.yml
test/models/customer_test.rb

Devise customer

---

app/assets/javascripts/admin/genres.coffee
app/assets/stylesheets/admin/genres.scss
app/controllers/admin/genres_controller.rb
app/helpers/admin/genres_helper.rb
app/models/genre.rb
app/views/admin/genres/edit.html.erb
app/views/admin/genres/index.html.erb
config/routes.rb
db/migrate/20210816103458_create_genres.rb
db/schema.rb
test/controllers/admin/genres_controller_test.rb
test/fixtures/genres.yml
test/models/genre_test.rb

[Add]ジャンルモデル/コンフリクト解消

---

app/models/item.rb
db/migrate/20210816102847_create_items.rb
db/schema.rb
test/fixtures/items.yml
test/models/item_test.rb

すみません。
一度リクエストしましたが外部キー制約が抜けており再度リクエストしています。
現在、closeにしています。

商品モデル、カラム、外部キーを追加しました

---

app/controllers/application_controller.rb
app/controllers/customers/confirmations_controller.rb
app/controllers/customers/omniauth_callbacks_controller.rb
app/controllers/customers/passwords_controller.rb
app/controllers/customers/registrations_controller.rb
app/controllers/customers/sessions_controller.rb
app/controllers/customers/unlocks_controller.rb
app/views/customers/registrations/new.html.erb
config/routes.rb

devise controllers作成時にミスがありましたため、訂正いたしました。ご迷惑おかけします。

[fix]devise controllersでの記述ミスを修正

---

app/controllers/admin/confirmations_controller.rb
app/controllers/admin/omniauth_callbacks_controller.rb
app/controllers/admin/passwords_controller.rb
app/controllers/admin/registrations_controller.rb
app/controllers/admin/sessions_controller.rb
app/controllers/admin/unlocks_controller.rb
app/controllers/customer/confirmations_controller.rb
app/controllers/customer/omniauth_callbacks_controller.rb
app/controllers/customer/passwords_controller.rb
app/controllers/customer/registrations_controller.rb
app/controllers/customer/sessions_controller.rb
app/controllers/customer/unlocks_controller.rb
app/views/customers/registrations/new.html.erb
config/routes.rb

アプリケーション詳細設計通りにコントローラの参照先をへんこうしました。

[fix]コントローラ参照先の修正

---

app/models/order.rb
db/migrate/20210817122926_create_orders.rb
db/schema.rb
test/fixtures/orders.yml
test/models/order_test.rb

Order model を作成しました。
カラム名、enum、デフォルト値　問題なければMargeをお願いします。

[Add]Order model

---

app/models/cart_item.rb
app/models/order.rb
db/migrate/20210817122926_create_orders.rb
db/migrate/20210817124624_create_cart_items.rb
db/schema.rb
test/fixtures/cart_items.yml
test/fixtures/orders.yml
test/models/cart_item_test.rb
test/models/order_test.rb

CartItem model を作成しました。
Order mode の確認を先にお願いいたします。schema.rb のコンクリフト対策です。
Order が問題なければ、こちらの確認、Marge をお願いいたします。

Cart items create

---

app/assets/javascripts/public/customers.coffee
app/assets/stylesheets/public/customers.scss
app/controllers/application_controller.rb
app/controllers/public/customers_controller.rb
app/helpers/public/customers_helper.rb
app/views/customers/registrations/new.html.erb
app/views/customers/sessions/new.html.erb
app/views/layouts/_header.html.erb
app/views/public/customers/edit.html.erb
app/views/public/customers/show.html.erb
config/routes.rb
test/controllers/public/customers_controller_test.rb

[add]customer/showページ作成[fix]ログインページの乱れを修正

---

app/assets/javascripts/public/items.coffee
app/assets/stylesheets/public/items.scss
app/controllers/public/items_controller.rb
app/helpers/public/items_helper.rb
app/models/item.rb
app/views/admin/items/edit.html.erb
app/views/admin/items/index.html.erb
app/views/admin/items/new.html.erb
app/views/admin/items/show.html.erb
app/views/public/items/index.html.erb
app/views/public/items/show.html.erb
config/routes.rb
test/controllers/public/items_controller_test.rb

デザインは後で整えます。
カートの遷移先の確認が行えていないのでHAMOさんお願いします。

会員側の商品のviewとcontrollerの作成を行いました。

---

db/migrate/20210818110142_chenge_not_null.rb
db/schema.rb

device関係のNotNullを取り消しました。
直接ご説明しますが、こちらをマージしていただければ新規登録できます。

[Update]NotNullの修正

---

app/controllers/public/customers_controller.rb
app/controllers/public/sessions_controller.rb
app/models/customer.rb
app/views/layouts/application.html.erb
app/views/public/customers/edit.html.erb
app/views/public/customers/secession.html.erb
app/views/public/customers/show.html.erb
config/routes.rb

カスタマーページを作成しました。仕様について列挙します。
・show、edit、退会確認画面を作成しました。同時にupdate、退会処理も作成しました。
・customerモデルにvalidatesを記述しました。詳細はご確認ください。
・退会したcustomerは二度とログインできなくなりました。（余裕があれば復活処理も導入したいですね）
・application.htmlにフラッシュメッセージを導入しました。flash[:notice]を表示するようにしております。これにより、各種成功時にはメッセージが表示されます。

[add]カスタマーページ（show,edit,update,退会機能）完成

---

app/controllers/admin/genres_controller.rb
app/controllers/application_controller.rb

Genre create

---

app/controllers/public/orders_controller.rb
app/models/cart_item.rb
app/models/item.rb
app/views/admin/items/show.html.erb
app/views/layouts/_header.html.erb
app/views/public/cart_items/index.html.erb
app/views/public/items/index.html.erb
app/views/public/orders/check.html.erb
app/views/public/orders/new.html.erb
db/migrate/20210820070947_rename_payment_integer_column_to_orders.rb
db/schema.rb

[update]hesderのルーティングの更新

---

app/assets/stylesheets/application.scss
app/views/layouts/_footer.html.erb
app/views/layouts/_header.html.erb
app/views/layouts/application.html.erb

・header, footerについて画像を挿入、位置を調整しました。
・詳しくはコメントアウトに記載をしております。

[add]レイアウト修正

---

app/controllers/admin/customers_controller.rb
app/controllers/admin/genres_controller.rb
app/controllers/admin/homes_controller.rb
app/controllers/admin/items_controller.rb
app/controllers/admin/orders_controller.rb
app/controllers/application_controller.rb
app/views/public/items/show.html.erb
app/views/public/orders/new.html.erb

show ページですでにカートに入れている時のボタンを変更
管理者としてログインしていない場合、root_path にリダイレクトするようにメソッドを記載

Item create

---

app/controllers/public/items_controller.rb
app/views/public/homes/_card_deck.html.erb
app/views/public/homes/_genres_search.html.erb
app/views/public/homes/top.html.erb
app/views/public/items/index.html.erb

[Add]商品一覧作成

---

app/views/public/orders/check.html.erb

確認画面で支払方法・お届け先が表示されていなかったので表示させました。

[Update]viwes/public/orders/check

---

app/controllers/public/items_controller.rb
app/views/layouts/_search.html.erb
app/views/public/items/index.html.erb
app/views/public/items/show.html.erb

[Add]Item show

---

app/assets/stylesheets/admin/items.scss
app/views/admin/items/edit.html.erb
app/views/admin/items/index.html.erb
app/views/admin/items/new.html.erb
app/views/admin/items/show.html.erb

管理者側の商品一覧に商品追加ボタンを追加しました。
少しデザインも整えました。

管理者側の商品一覧に商品追加ボタンを追加

---

app/controllers/public/orders_controller.rb
app/models/customer.rb
app/models/order.rb
app/views/public/orders/index.html.erb
app/views/public/orders/show.html.erb

OrderItem のテーブルに保存されるように修正
OrderItem の保存がカート内商品の数行われていなかったので合わせて修正
顧客側の注文履歴の表示を作成

Order items create

---

app/models/address.rb
app/models/cart_item.rb
app/models/order.rb
app/models/order_item.rb

[Add]model-validates

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/stylesheets/application.scss
app/controllers/public/items_controller.rb
app/views/layouts/application.html.erb
app/views/public/customers/edit.html.erb
app/views/public/customers/secession.html.erb
app/views/public/customers/show.html.erb
app/views/public/homes/_card_deck.html.erb
app/views/public/homes/top.html.erb

更新事項を列挙します。
・【注意】turbolinksを削除しました。pull後にbundleの更新をお願いします。
・商品を表示するcard機能にマウスをホバーすると、拡大、縮小するようにしました。
・フラッシュメッセージを見やすく変更しました。５秒経過すると見えなくなる仕様にしております。
・商品詳細画面のフラッシュメッセージを追加しました。
具体的には、誰かがその商品を過去に注文した場合、誰かがその商品をカートに入れている場合に、
何人が~している、とフラッシュメッセージが表示されます。

[add]jqueryを用いた、レイアウトの全体的な更新

---

app/views/admin/genres/edit.html.erb
app/views/admin/genres/index.html.erb
app/views/public/cart_items/index.html.erb
app/views/public/orders/index.html.erb
app/views/public/orders/show.html.erb

[Update]layout

---

app/views/public/cart_items/index.html.erb

[Update]カートに商品がないと情報入力に進めないように修正

---

app/models/item.rb
app/views/admin/items/edit.html.erb
app/views/admin/items/new.html.erb
app/views/public/orders/index.html.erb

デザインの修正
値段をintegerのみしか記入できないように変更

デザインを少し修正しました

---

app/assets/stylesheets/application.scss
app/views/layouts/_footer.html.erb
app/views/layouts/_header.html.erb
app/views/public/homes/_genres_search.html.erb

headerの画像をTopページとそれ以外で変化するようにしました
ジャンル検索にマウスカーソルを合わせると項目が黒くなるようにしました

[Fix]Topページのレイアウト変更とジャンルのhover設定

---

app/controllers/public/addresses_controller.rb
app/controllers/public/cart_items_controller.rb
app/controllers/public/customers_controller.rb
app/controllers/public/orders_controller.rb

ログインしていないときに、マイページにアクセスせずログイン画面に遷移するようにしました。

[fix]未ログイン時の挙動を修正

---

app/controllers/application_controller.rb
app/controllers/public/orders_controller.rb
app/views/admin/items/edit.html.erb
app/views/public/cart_items/index.html.erb
app/views/public/items/show.html.erb
app/views/public/orders/new.html.erb

管理者ログアウトの後、ログイン画面に遷移していない
買い物を続けるの後、トップ画面に遷移していない
買い物の住所選択でデフォルトで自身の住所を選択させたほうが良いかも？
販売停止中の商品も追加できてしまう
注文を確定する前に新しい配達先が登録されてしまっていた
以上修正しました。

[Update]テスト要件に合わせて修正/ほか、レイアウト等修正

---

app/controllers/public/cart_items_controller.rb
app/controllers/public/orders_controller.rb
app/views/admin/customers/index.html.erb
app/views/admin/items/edit.html.erb
app/views/admin/items/index.html.erb
app/views/admin/items/new.html.erb
app/views/admin/items/show.html.erb
app/views/admin/orders/show.html.erb
app/views/public/items/show.html.erb
app/views/public/orders/show.html.erb

[Update]修正

---

app/controllers/public/orders_controller.rb

[Update]修正漏れ
